# Generated by Django 4.1.3 on 2022-11-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_purpose',
            field=models.CharField(choices=[('G', 'Набор веса'), ('L', 'Похудение')], default='G', max_length=1),
        ),
    ]
