# Generated by Django 4.1.3 on 2022-11-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.DateField(auto_now_add=True, verbose_name='День тренировки'),
        ),
    ]
