# Generated by Django 4.1.3 on 2022-11-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0002_alter_workout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='muscle_groups',
            field=models.ManyToManyField(default=None, to='workout_tracker.musclegroup', verbose_name='Группы мышц'),
        ),
    ]
