# Generated by Django 4.1.3 on 2022-11-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0003_workout_muscle_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workout_tracker/photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='muscle_groups',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='workout_tracker.musclegroup', verbose_name='Группы мышц'),
        ),
    ]
