# Generated by Django 4.1.3 on 2022-11-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0003_alter_dish_options_alter_meal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(default=None, upload_to='calorie_tracker/photos/'),
        ),
    ]
