# Generated by Django 4.1.3 on 2022-11-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0005_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='calorie_tracker/photos/'),
        ),
    ]
