# Generated by Django 4.1.3 on 2022-11-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0008_alter_dish_image_alter_dish_protein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
