# Generated by Django 4.1.3 on 2022-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0010_product_meal_id_alter_dish_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='fat',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Белки'),
        ),
    ]
