# Generated by Django 4.1.3 on 2022-11-08 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calorie_tracker', '0011_alter_dish_carbohydrates_alter_dish_fat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['id'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['id'], 'verbose_name': 'Приём пищи', 'verbose_name_plural': 'Приёмы пищи'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_time',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7)),
                ('entry_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вес',
                'verbose_name_plural': 'Вес',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_calories', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total_protein', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total_fat', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total_carbohydrates', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('day', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie_tracker.day'),
            preserve_default=False,
        ),
    ]
