# Generated by Django 4.1.3 on 2022-11-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0012_alter_dish_options_alter_meal_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dish_id',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='meal_id',
            new_name='meal',
        ),
    ]
