# Generated by Django 4.1.3 on 2022-11-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0013_rename_dish_id_product_dish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.IntegerField(default=0, verbose_name='Калории'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day',
            name='total_calories',
            field=models.IntegerField(verbose_name='Калории'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='total_calories',
            field=models.IntegerField(verbose_name='Калории'),
        ),
    ]
